name: pbns
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - matplotlib
  - tqdm
  - pip:
      - tensorflow-macos==2.16.2
      - tensorflow-metal==1.1.0
      - scipy==1.13.0
      - setuptools==65.7.0
      - chumpy==0.70
      - tensorflow-graphics==2021.12.3
